---
- hosts: localhost
  vars:
    my_version: "{{ version }}"
  tasks:
  - name: Backup older Jar
    copy: 
      src: /opt/gs-spring-boot.jar
      dest: /opt/gs-spring-boot-bkp.jar
      force: yes

  - name: copy Application jar to /opt
    copy:
      src: /opt/springboohello-CICD/target/gs-spring-boot-{{ my_version }}.jar
      dest: /opt/gs-spring-boot-{{ my_version }}.jar
      force: yes
      mode: 0755

  - name: Create soft link from old to new version
    file:
     src: /opt/gs-spring-boot-{{ my_version }}.jar
     dest: /opt/gs-spring-boot.jar
     state: link
     force: yes

  - name : Helloworld template
    template:
      src: helloworld.service.j2
      dest: ./helloworld.service

  - name: Copy Helloworld service from local to remote
    copy:
      src: ./helloworld.service
      dest: /etc/systemd/system/
      mode: 0755

  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes

  - name: enable helloworld startup
    service:
      name: helloworld
      state: restarted
