- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

- name: start tomcat
  service: name=helloworld state=started

- name: wait for helloworld application to be available
  wait_for: port=33333 delay=20
