- name: stop helloworld
  service: name=helloworld state=stopped

- name: Backup older Jar
  copy:
    src: /opt/gs-spring-boot.jar
    dest: /opt/gs-spring-boot-bkp.jar
    force: yes

- name: copy Application jar to /opt
  copy:
    src: /opt/springboohello-CICD/target/gs-spring-boot-{{ my_version }}.jar
    dest: /opt/gs-spring-boot-{{ my_version }}.jar
    force: yes
    mode: 0755

- name: Create soft link from old to new version
  file:
   src: /opt/gs-spring-boot-{{ my_version }}.jar
   dest: /opt/gs-spring-boot.jar
   state: link
   force: yes

- name: check if helloworld service created
  stat: path="/etc/systemd/system/helloworld.service"
  register: st

- name : Helloworld template
  template:
    src: helloworld.service.j2
    dest: ./helloworld.service
  when: st.stat.exists == False

- name: Copy Helloworld service from local to remote
  copy:
    src: ./helloworld.service
    dest: /etc/systemd/system/
    mode: 0755
  when: st.stat.exists == False

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes
  when: st.stat.exists == False
